---
all:
  children:
    k3s_servers:
      hosts:
        gpu-cp01:
          ansible_host: 192.168.8.130
          node_role: single-node-gpu
    k3s_agents:
      hosts: {}
    gpu_nodes:
      children:
        k3s_servers:
    gpu_cluster:
      children:
        k3s_servers:
