---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: OCIRepository
metadata:
  name: tts-service-chart
  namespace: tts
spec:
  interval: 1h
  url: oci://ghcr.io/liyinbo/charts/tts-service
  ref:
    digest: sha256:394ea5dc51017be4dbbf6ee5d3f194bb27217d6d4e20528ecb98df8de4d38908
