---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: gpu-ops
  namespace: flux-system
spec:
  interval: 1m
  ref:
    branch: main
  secretRef:
    name: gpu-ops-forgejo
  url: https://forgejo.home.hope-leniency.com/limbo/gpu_ops.git
