---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: meta-harness
  namespace: meta-harness
spec:
  interval: 30m
  url: https://forgejo.home.hope-leniency.com/api/packages/limbo/helm
  secretRef:
    name: forgejo-helm
