---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vault-audit
  namespace: vault
  annotations:
    kustomize.toolkit.fluxcd.io/prune: disabled
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: vault-local
  resources:
    requests:
      storage: 1Gi
