---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - storageclass.yaml
  - audit-pvc.yaml
  - helmrepository.yaml
  - tls.yaml
  - networkpolicy.yaml
  - helmrelease.yaml
