name: Renovate

on:
  workflow_dispatch:
  schedule:
    - cron: '17 3 * * 1'

permissions:
  contents: write
  issues: write
  pull-requests: write

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - uses: renovatebot/github-action@v46.1.20
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
        env:
          RENOVATE_REPOSITORIES: ${{ github.repository }}
